# Generated by Django 6.1.1 on 2026-09-05 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=64, unique=True)),
                ("phonetic", models.CharField(blank=True, default="", max_length=128)),
                ("pos", models.CharField(blank=True, default="", max_length=64)),
                ("meaning", models.TextField(blank=True, default="")),
                ("example", models.TextField(blank=True, default="")),
                ("example_cn", models.TextField(blank=True, default="")),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("freq_read", models.IntegerField(default=0)),
                ("freq_listen", models.IntegerField(default=0)),
                ("freq_translate", models.IntegerField(default=0)),
                ("freq_write", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=2)),
                ("mnemonic", models.TextField(blank=True, default="")),
                ("collocations", models.JSONField(blank=True, default=list)),
                ("confusables", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.IntegerField(default=3)),
                ("review_type", models.CharField(default="learn", max_length=16)),
                ("topic", models.CharField(blank=True, default="", max_length=16)),
                ("is_correct", models.BooleanField(default=True)),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_records",
                        to="core.word",
                    ),
                ),
            ],
            options={
                "ordering": ["-answered_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.IntegerField(default=0)),
                ("ease", models.FloatField(default=2.5)),
                ("interval_minutes", models.IntegerField(default=0)),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("lapses", models.IntegerField(default=0)),
                ("wrong_count", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("last_quality", models.IntegerField(default=-1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_states",
                        to="core.word",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "word")},
            },
        ),
    ]
